// Autogenerated - DO NOT EDIT

#include <stdint.h>
#pragma once

struct {
	char* url;
	uint64_t timestamp;
} dbx_info[] = {
	{ "https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/SignedByKEK2023/dbx_ia32.efiauth2", 1788300339 },
	{ "https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/SignedByKEK2023/dbx_x64.efiauth2", 1788300339 },
	{ "https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/SignedByKEK2023/dbx_arm.efiauth2", 1788300339 },
	{ "https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/SignedByKEK2023/dbx_aarch64.efiauth2", 1788300339 },
	{ "https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/SignedByKEK2023/dbx_ia64.efiauth2", 0 },
	{ "https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/SignedByKEK2023/dbx_riscv64.efiauth2", 0 },
	{ "https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/SignedByKEK2023/dbx_loongarch64.efiauth2", 0 },
};
